### ISSUE TITLE
Duplicate results

### ISSUE THREAD

**Issue by chmac** [acemtp/meteor-fastosphere#10]
First off, thanks for an awesome tool. It's nice to jump right to the GitHub pages instead of atmosphere, and not having to wait for that massive boot time on atmospherejs.com is a big win.

I've noticed that some searches return the same package more than once at different versions. For example a search for `blog` shows up the `ryw:blog` package twice, version `0.6.1` and `0.8.4`.

**Comment by acemtp** [comment]
Thanks for the feedback!

We plan to upgrade it soon and fix this issue

**Comment by acemtp** [comment]
Don't hesitate if you have ideas or things you would love to see

**Comment by chmac** [comment]
My only other challenge is the download / active install count. They seem to be out of sync with atmospherejs.com, but that looks like it's addressed in #8.

I typically reach for fastosphere first, and then check atmosphere to be sure I'm seeing everything, get the install counts, and so on.

**Comment by acemtp** [comment]
Thank. I'll also look at that

**Comment by acemtp** [comment]
package duplication is fixed!
