### ISSUE TITLE
Requested feature: go back button

### ISSUE THREAD

**Issue by VioletaCalvo** [acemtp/meteor-fastosphere#12]
Hi!

On main package list view number of downloads and github starts are shown, but this info is not shown in the package view. It could be very useful to go back to the main view to search another package.

Thank you for this project! :blush:

**Comment by acemtp** [comment]
You can go back just by clicking again on the package you selected, it's a toogle (not straightforward I agree).

**Comment by VioletaCalvo** [comment]
OK! Thank you!
