### ISSUE TITLE
CHANGELOG not working

### ISSUE THREAD

**Issue by ffxsam** [acemtp/meteor-fastosphere#14]
My package `ffxsam:react-smartform` has a CHANGELOG.md file, yet Fastosphere says there is none.

**Comment by peernohell** [comment]
Information is not checked in realtime. maybe it was juste not updated at the moment you have look but now it seems present 
http://fastosphere.meteor.com/ffxsam%253Areact-smartform?q=ffxsam%3Areact-smartform
