### ISSUE TITLE
Below 1200px wide, layout = bad user experience

### ISSUE THREAD

**Issue by ffxsam** [acemtp/meteor-fastosphere#16]
http://fastosphere.meteor.com/joncursi%253Asocket-io-client

Below 1200px wide, the related search results are at 100% width above the actual package details. This is confusing, it makes it seem like clicking the package to drill into the detail view did not work.

I'd recommend putting the package details first, with related search results underneath.

**Comment by acemtp** [comment]
thank for the report.
it should be better
