### ISSUE TITLE
Hosted somewhere now?

### ISSUE THREAD

**Issue by chmac** [acemtp/meteor-fastosphere#18]
Is fastosphere running somewhere else now that meteor.com hosting has gone offline?

**Comment by acemtp** [comment]
we asked meteor to see what they can do

**Comment by chmac** [comment]
Any idea what the traffic was like? We could maybe whip up some hosting for it...

**Comment by acemtp** [comment]
Thank you. You can follow the progress here: https://github.com/meteor/guide/issues/409#issuecomment-215927458

**Comment by acemtp** [comment]
It's now here: http://fastosphere.meteorapp.com/
