### ISSUE TITLE
Download counts are different from Atmosphere

### ISSUE THREAD

**Issue by msavin** [acemtp/meteor-fastosphere#8]
Hey man - nice project :) 

I did a quick look for my packages, Mongol and ToyKit. 
On Atmosphere, they have 60k downloads and 0k downloads, respectively.
On Fastosphere, they have about 14k each.
Both are on the correct version numbers, etc.

ToyKit is a dependency, so it's download count does not go up unless it was intentionally installed.

I'm curious where the discrepancy lies - perhaps Fastophere has unique downloads instead of total downloads?

Best,
Max

**Comment by acemtp** [comment]
Hi man - thank you :)

Honestly I don't compare stats between atmo and fasto :)

We use the stat meteor gave us : https://github.com/acemtp/meteor-fastosphere/blob/f10ea908dda49f8bafda66b94502eb6f8c1ecf4a/server/meteorstat.js

There's totaldl and directdl, that could explain.

**Comment by wildeyes** [comment]
Hello @acemtp, general unrelated-question, where did you get the docs for packages.meteor.com?

**Comment by acemtp** [comment]
@wildeyes from here https://github.com/meteor/meteor/wiki/Meteor-Package-Server-API

**Comment by acemtp** [comment]
Should be fixed in the new version!
