### ISSUE TITLE
algolia-search deprecated

### ISSUE THREAD

**Issue by louwers** [acemtp/meteor-fastosphere#9]
```
npm WARN deprecated algolia-search@1.7.7: Please use the isomorphic `algoliasearch` package. See our migration guide at https://github.com/algolia/algoliasearch-client-js/wiki/Node.js-v1.x.x-migration-guide
```

![screen shot 2015-08-31 at 0 17 26](https://cloud.githubusercontent.com/assets/649392/9569790/b3aca4f4-4f75-11e5-9ce4-1163bb6d2b53.png)

When installed.

**Comment by acemtp** [comment]
Thanks for the feedback, I'll check that

**Comment by acemtp** [comment]
I used now the latest version of algolia. should be fixed if you update fastosphere npm package
